
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.groupBox.setObjectName("groupBox")
        self.block3 = QtWidgets.QRadioButton(self.centralwidget)
        self.block3.setGeometry(QtCore.QRect(150, 40, 95, 20))
        self.block3.setObjectName("block3")
        self.block1 = QtWidgets.QRadioButton(self.centralwidget)
        self.block1.setGeometry(QtCore.QRect(30, 40, 95, 20))
        self.block1.setObjectName("block1")
        self.block2 = QtWidgets.QRadioButton(self.centralwidget)
        self.block2.setGeometry(QtCore.QRect(90, 40, 31, 20))
        self.block2.setObjectName("block2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 231, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.arange = QtWidgets.QLineEdit(self.centralwidget)
        self.arange.setGeometry(QtCore.QRect(110, 190, 113, 22))
        self.arange.setObjectName("arange")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 71, 16))
        self.label_3.setObjectName("label_3")
        self.brange = QtWidgets.QLineEdit(self.centralwidget)
        self.brange.setGeometry(QtCore.QRect(110, 250, 113, 22))
        self.brange.setObjectName("brange")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 310, 71, 16))
        self.label_4.setObjectName("label_4")
        self.crange = QtWidgets.QLineEdit(self.centralwidget)
        self.crange.setGeometry(QtCore.QRect(110, 310, 113, 22))
        self.crange.setObjectName("crange")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label.setObjectName("label")
        self.pls = QtWidgets.QLineEdit(self.centralwidget)
        self.pls.setGeometry(QtCore.QRect(110, 130, 113, 22))
        self.pls.setObjectName("pls")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 231, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_6.setObjectName("label_6")
        self.metal2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.metal2.setGeometry(QtCore.QRect(100, 110, 113, 22))
        self.metal2.setObjectName("metal2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_7.setObjectName("label_7")
        self.metal3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.metal3.setGeometry(QtCore.QRect(100, 170, 113, 22))
        self.metal3.setObjectName("metal3")
        self.metal1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.metal1.setGeometry(QtCore.QRect(100, 50, 113, 22))
        self.metal1.setObjectName("metal1")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(10, 650, 93, 28))
        self.submit.setObjectName("submit")
        self.show = QtWidgets.QPushButton(self.centralwidget)
        self.show.setGeometry(QtCore.QRect(110, 650, 93, 28))
        self.show.setObjectName("show")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(220, 650, 93, 28))
        self.generate.setObjectName("generate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "BLOCK"))
        self.block3.setText(_translate("MainWindow", "3"))
        self.block1.setText(_translate("MainWindow", "1"))
        self.block2.setText(_translate("MainWindow", "2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "PLS and Ranges"))
        self.label_3.setText(_translate("MainWindow", "B Value"))
        self.label_4.setText(_translate("MainWindow", "C Value"))
        self.label_2.setText(_translate("MainWindow", "A Value"))
        self.label.setText(_translate("MainWindow", "PLS Name"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Metals"))
        self.label_8.setText(_translate("MainWindow", "metal 3"))
        self.label_6.setText(_translate("MainWindow", "metal 1"))
        self.label_7.setText(_translate("MainWindow", "metal 2"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.show.setText(_translate("MainWindow", "show"))
        self.generate.setText(_translate("MainWindow", "generate"))
